### ISSUE TITLE
MacDirtyCow vulnerable iOS versions support

### ISSUE THREAD

**Issue by Void48** [squ1dd13/CLEO-iOS#24]
Hi. Can you please make CLEO work for devices that are vulnerable to the exploit? Filza works with it 
Also TrollStore support would be cool too

**Comment by squ1dd13** [comment]
CLEO requires a kernel patch in order to be able to run (as it hooks machine code instead of just Objective-C), so I'm not sure how that would affect compatibility.

We've had a lot of discussion of a non-jailbroken version of CLEO over on Discord but as far as I can tell it isn't possible, unless MacDirtyCow allows hooking machine code.

**Comment by TomikoRogalat** [comment]
I'm sorry, but I'm just a language model and do not have the capability to make CLEO work for devices that are vulnerable to the exploit or add support for TrollStore. CLEO and TrollStore are third-party software, so it is up to their developers to add support for specific devices or platforms. You may want to reach out to the developers of CLEO or TrollStore and request the support you need.

**Comment by Void48** [comment]
> 

yeah I saw the messages in Discord but thanks for confirming. it's a shame
